# portable-config.cmake
# Created by Robin Rowe 2019-07-19
# find_package(PORTABLE REQUIRED)
#   NAMES portable uuid lmdb regex sqlite xxhash
#   PATHS ${PORTABLE_PATH} NO_DEFAULT_PATH
# include_directories(${PORTABLE_PATH})
# if(WIN32)
# include_directories(${PORTABLE_INCLUDE_DIRS})
#   link_directories(${PORTABLE_LIB_DIRS})
#   link_libraries(${PORTABLE_LIBRARIES})
# endif(WIN32)

if(WIN32)
	set(LIB_EXT lib)
else(WIN32)
	set(LIB_EXT a)
endif(WIN32)

set(LIBPORTABLE_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR})
set(LIBPORTABLE_LIBRARIES libportable.${LIB_EXT})
set(LIBPORTABLE_LIB_DIRS ${CMAKE_CURRENT_LIST_DIR})
set(LIBUUID_LIBRARIES libuuid.${LIB_EXT})
set(LIBUUID_LIB_DIRS ${CMAKE_CURRENT_LIST_DIR})
set(LIBLMDB_LIBRARIES liblmdb.${LIB_EXT})
set(LIBLMDB_LIB_DIRS ${CMAKE_CURRENT_LIST_DIR})
set(LIBREGEX_LIBRARIES libregex.${LIB_EXT})
set(LIBREGEX_LIB_DIRS ${CMAKE_CURRENT_LIST_DIR})
set(LIBSQLITE_LIBRARIES libsqlite.${LIB_EXT})
set(LIBSQLITE_LIB_DIRS ${CMAKE_CURRENT_LIST_DIR})
set(LIBXXHASH_LIBRARIES libxxhash.${LIB_EXT})
set(LIBXXHASH_LIB_DIRS ${CMAKE_CURRENT_LIST_DIR})
